name: Minify & Release
on:
  push:
    branches:
      - release

jobs:
  minify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install python-minifier
        run: pip install python-minifier

      - name: Minify
        run: python tools/minify.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: release-minified
          path: out/
