name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    
    - name: Clone micropython stubs
      run: git clone https://github.com/Josverl/micropython-stubs.git
    
    - name: Analysing the code with pylint
      env:
        PYTHONPATH: ./micropython-stubs/stubs/micropython-v1_23_0-esp32-ESP32_GENERIC
      run: |
        pylint $(git ls-files '*.py')
